# Pytorch Basic Tensor & Cuda
---
by Pranpaveen Lay.

In [1]:
import torch

In [2]:
torch.__version__

'1.8.0'

In [3]:
torch.cuda.is_available()

True

# Tensor
- multidimension array

In [4]:
# 0d SCALAR
t0 = torch.tensor(2)
t0

tensor(2)

In [14]:
t0.shape

torch.Size([])

In [5]:
# 1d VECTOR
t1 = torch.tensor([1,2,3])
t1

tensor([1, 2, 3])

In [13]:
t1.shape

torch.Size([3])

In [7]:
# 2d MATRIX
t2 = torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
t2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
t2.shape

torch.Size([3, 3])

In [10]:
# 3d array

t3 = torch.tensor([[[1,2,3],
                    [4,5,6]],
                   
                   [[7,8,9],
                    [10,11,12]]])
t3

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [11]:
t3.shape

torch.Size([2, 2, 3])

numpy like method

In [17]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [18]:
b = torch.zeros(2,2)
b

tensor([[0., 0.],
        [0., 0.]])

In [23]:
c = torch.rand(3,3)
c

tensor([[0.1147, 0.0107, 0.4205],
        [0.7965, 0.9811, 0.4782],
        [0.2475, 0.5426, 0.4526]])

In [24]:
c[:,0]

tensor([0.1147, 0.7965, 0.2475])

In [25]:
c[0,:]

tensor([0.1147, 0.0107, 0.4205])

In [27]:
c.shape

torch.Size([3, 3])

In [49]:
d = torch.rand(3,2,names=['x','y'])
d

tensor([[0.8468, 0.2820],
        [0.6826, 0.5900],
        [0.8298, 0.5623]], names=('x', 'y'))

In [50]:
d.shape,d.names

(torch.Size([3, 2]), ('x', 'y'))

## Data Type

In [51]:
d.type()

'torch.FloatTensor'

In [58]:
d = d.to(torch.double)
d

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64, names=('x', 'y'))

In [59]:
d.type()

'torch.DoubleTensor'

In [60]:
e = torch.rand(3,2,dtype=torch.float16)
e

tensor([[0.9312, 0.3682],
        [0.8921, 0.0781],
        [0.7368, 0.2925]], dtype=torch.float16)

In [61]:
e.type()

'torch.HalfTensor'

# Tensor with GPU (CUDA)

In [128]:
torch.cuda.is_available()

True

In [102]:
!nvidia-smi -q -d MEMORY


==============NVSMI LOG==============

Timestamp                                 : Tue Jan 11 16:57:27 2022
Driver Version                            : 472.56
CUDA Version                              : 11.4

Attached GPUs                             : 1
GPU 00000000:01:00.0
    FB Memory Usage
        Total                             : 6144 MiB
        Used                              : 1459 MiB
        Free                              : 4685 MiB
    BAR1 Memory Usage
        Total                             : 8192 MiB
        Used                              : 1 MiB
        Free                              : 8191 MiB



In [104]:
t_cpu = torch.rand(3,3)
t_cpu

tensor([[0.3500, 0.7205, 0.9091],
        [0.6437, 0.9298, 0.1852],
        [0.8199, 0.1564, 0.4672]])

In [105]:
t_gpu = t_cpu.cuda()

In [107]:
t_gpu

tensor([[0.3500, 0.7205, 0.9091],
        [0.6437, 0.9298, 0.1852],
        [0.8199, 0.1564, 0.4672]], device='cuda:0')

In [114]:
t_cpu.to('cuda')

tensor([[0.3500, 0.7205, 0.9091],
        [0.6437, 0.9298, 0.1852],
        [0.8199, 0.1564, 0.4672]], device='cuda:0')

In [115]:
t_gpu.cpu()

tensor([[0.3500, 0.7205, 0.9091],
        [0.6437, 0.9298, 0.1852],
        [0.8199, 0.1564, 0.4672]])

In [116]:
!nvidia-smi -q -d MEMORY


==============NVSMI LOG==============

Timestamp                                 : Tue Jan 11 16:59:50 2022
Driver Version                            : 472.56
CUDA Version                              : 11.4

Attached GPUs                             : 1
GPU 00000000:01:00.0
    FB Memory Usage
        Total                             : 6144 MiB
        Used                              : 2007 MiB
        Free                              : 4137 MiB
    BAR1 Memory Usage
        Total                             : 8192 MiB
        Used                              : 1 MiB
        Free                              : 8191 MiB



In [120]:
a = torch.rand(255,255,device='cuda')

In [121]:
a

tensor([[0.4671, 0.1293, 0.5869,  ..., 0.6189, 0.1071, 0.6067],
        [0.8836, 0.7016, 0.9172,  ..., 0.8073, 0.7738, 0.2586],
        [0.1593, 0.4490, 0.1228,  ..., 0.1260, 0.1936, 0.6967],
        ...,
        [0.8343, 0.3579, 0.1950,  ..., 0.9405, 0.7871, 0.5577],
        [0.5796, 0.5153, 0.9896,  ..., 0.1911, 0.0829, 0.6288],
        [0.7541, 0.5192, 0.9094,  ..., 0.5090, 0.7381, 0.9705]],
       device='cuda:0')

In [123]:
!nvidia-smi -q -d MEMORY


==============NVSMI LOG==============

Timestamp                                 : Tue Jan 11 17:00:54 2022
Driver Version                            : 472.56
CUDA Version                              : 11.4

Attached GPUs                             : 1
GPU 00000000:01:00.0
    FB Memory Usage
        Total                             : 6144 MiB
        Used                              : 2027 MiB
        Free                              : 4117 MiB
    BAR1 Memory Usage
        Total                             : 8192 MiB
        Used                              : 1 MiB
        Free                              : 8191 MiB



In [124]:
b = torch.rand(255,255)

In [125]:
a+b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [126]:
a + b.cuda()

tensor([[1.2349, 0.7295, 0.6815,  ..., 1.5631, 0.8300, 1.0523],
        [0.9990, 1.3701, 1.5639,  ..., 1.0784, 1.4541, 0.8637],
        [1.0398, 1.2898, 0.6565,  ..., 0.3882, 0.2094, 0.8458],
        ...,
        [0.9306, 0.5657, 0.2145,  ..., 1.8956, 1.7528, 0.7059],
        [0.7385, 0.9536, 1.6418,  ..., 0.9217, 0.6803, 1.2020],
        [1.2648, 0.5691, 1.0409,  ..., 0.7158, 1.7009, 1.8150]],
       device='cuda:0')

In [127]:
a.cpu() + b

tensor([[1.2349, 0.7295, 0.6815,  ..., 1.5631, 0.8300, 1.0523],
        [0.9990, 1.3701, 1.5639,  ..., 1.0784, 1.4541, 0.8637],
        [1.0398, 1.2898, 0.6565,  ..., 0.3882, 0.2094, 0.8458],
        ...,
        [0.9306, 0.5657, 0.2145,  ..., 1.8956, 1.7528, 0.7059],
        [0.7385, 0.9536, 1.6418,  ..., 0.9217, 0.6803, 1.2020],
        [1.2648, 0.5691, 1.0409,  ..., 0.7158, 1.7009, 1.8150]])

In [129]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [132]:
b.to(device)

tensor([[0.7678, 0.6003, 0.0946,  ..., 0.9442, 0.7229, 0.4457],
        [0.1155, 0.6685, 0.6467,  ..., 0.2710, 0.6803, 0.6051],
        [0.8804, 0.8408, 0.5338,  ..., 0.2622, 0.0158, 0.1491],
        ...,
        [0.0962, 0.2079, 0.0195,  ..., 0.9551, 0.9657, 0.1482],
        [0.1589, 0.4383, 0.6522,  ..., 0.7306, 0.5973, 0.5732],
        [0.5106, 0.0499, 0.1315,  ..., 0.2068, 0.9629, 0.8444]],
       device='cuda:0')